### ISSUE TITLE
'default' list is difficult to read

### ISSUE THREAD

**Issue by amythetester** [mmcknett/loggr#33]
The text color of the list field is difficult to read when the form is first rendered. Selecting the same list in the drop down makes it much easier to read

**Comment by mmcknett** [comment]
Thanks for finding this! This is an issue with the placeholder color of the textbox.

The current contrast of this text is 2.43:1, and [it should be 4.5:1](https://accessibleweb.com/question-answer/does-placeholder-text-need-to-meet-color-contrast-requirements/). The foreground color #a6a6a6 should be sufficient for the placeholder text contrast.
